version: '3'
services:
  # MySQL
  db:
    image: mysql:8.0.36
    ports:
      - "3307:3306"
    container_name: bank-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=bank_db
