# Get all users
GET localhost:8080/users

###

# Get user by id
GET localhost:8080/users/1

###

# Create a new user
POST localhost:8080/users
Content-Type: application/json

{
  "name": "Kostas"
}

###

# Update an existing user
PUT localhost:8080/users/1
Content-Type: application/json

{
  "name": "John Doe",
  "balance": 1000
}

###

# Delete user
DELETE localhost:8080/users/1

###
